### ISSUE TITLE
Good NVS Quality

### ISSUE THREAD

**Issue by TwiceMao** [mlvlab/UP-NeRF#5]
@cmh1027  I found that your method is not very effective in camera pose optimization when there are not many angles of view, but the synthesis effect of new angles is also good. Why is this? Is it related to Appearance Embedding ?

**Comment by cmh1027** [comment]
appearance embedding is for color-inconsistency in wild images so it can not recover poor NVS quality from poorly optimized pose. There can be two candidates for the situation. First, estimation of poses is not correct due to wrong implemetation somewhere in our code (I'm not sure about where it would be). Second, near and far parameters are set to 0.1, 5.0 each. Maybe far parameter is too high for your dataset (I experiened similar situation in the past for Lincoln scene in Phototourism) You can scale it down to like 2.0.

**Comment by TwiceMao** [comment]
Thx for your kind reply~
